"""create check_ins table

Revision ID: b6cf38efb25a
Revises: ee6ff6c1157c
Create Date: 2026-08-21 17:03:35.289789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cf38efb25a'
down_revision: Union[str, None] = 'ee6ff6c1157c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('stress', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('social_connection', sa.Integer(), nullable=False),
    sa.Column('overall_wellbeing', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('energy BETWEEN 0 AND 100', name='ck_check_ins_energy_range'),
    sa.CheckConstraint('mood BETWEEN 0 AND 100', name='ck_check_ins_mood_range'),
    sa.CheckConstraint('overall_wellbeing BETWEEN 0 AND 100', name='ck_check_ins_overall_range'),
    sa.CheckConstraint('social_connection BETWEEN 0 AND 100', name='ck_check_ins_social_range'),
    sa.CheckConstraint('stress BETWEEN 0 AND 100', name='ck_check_ins_stress_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_ins_user_id_created_at', 'check_ins', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_ins_user_id_created_at', table_name='check_ins')
    op.drop_table('check_ins')
    # ### end Alembic commands ###
